### ISSUE TITLE
Multical 403 - No response from meter / Message is invalid

### ISSUE THREAD

**Issue by Chrisiesmit93** [matthijsvisser/kamstrup-402-mqtt#3]
I am trying to get this script to save it's output to MQTT, but it throws 2 different error's when I start the script
- No response from meter
- Message is invalid

I get those error when the meterhead is flat on the surface, and when I hold it about 1 cm above the normal place.

Also I see that the script is publishing values to MQTT, but I don't see them with MQTT browser (other MQTT stuff is working).

Some information:
root@kamstrup-01:~# ls -l /dev/serial/by-id
total 0
lrwxrwxrwx 1 root root 13 Feb 12 15:41 usb-FTDI_FT230X_Basic_UART_D308BOXH-if00-port0 -> ../../ttyUSB0

cloned the git in /opt/kamstrup
```
root@kampstrup-01:~# cat /opt/kamstrup/config.yaml
mqtt:
    host: 192.168.8.254
    port: 1883
    client: kamstrup
    topic: kamstrup
    qos: 0
    retain: False
    authentication: False
    username: mqtt
    password: <PASSWORD>
serial_device:
    com_port: /dev/ttyUSB0
kamstrup:
    parameters:
    - energy
    - volume
    - temp1
    - temp2
    poll_interval: 11
```
